# Generated by Django 5.2.11 on 2026-09-20 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem', models.CharField(choices=[('portal', 'Portal'), ('integration', 'Integração'), ('system', 'Sistema')], max_length=16)),
                ('origem_identificador', models.CharField(blank=True, max_length=255, null=True)),
                ('acao', models.CharField(max_length=100)),
                ('objeto_tipo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('antes', models.JSONField(blank=True, null=True)),
                ('depois', models.JSONField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
