# Generated by Django 5.2.11 on 2026-09-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanelaRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('key_hash', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField()),
                ('contagem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Janela de rate limit',
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash', 'window_start'), name='rate_limit_bucket_unico')],
            },
        ),
    ]
