# Generated by Django 5.2.11 on 2026-09-20 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licencas', '0011_alter_clientesistema_periodicidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Competência')),
                ('vencimento', models.DateField(verbose_name='Vencimento')),
                ('fim_carencia', models.DateField(verbose_name='Fim da carência')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor original')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=16, verbose_name='Status')),
                ('descricao', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('origem', models.CharField(default='scl', max_length=16, verbose_name='Origem')),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelamento', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas', to='licencas.clientesistema', verbose_name='Assinatura')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_canceladas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['vencimento', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('dia_vencimento', models.PositiveSmallIntegerField(default=5, verbose_name='Dia de vencimento')),
                ('dias_carencia', models.PositiveSmallIntegerField(default=0, verbose_name='Dias de carência')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64, verbose_name='Fuso horário')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_financeiras_alteradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração financeira',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('pago_em', models.DateTimeField(verbose_name='Pago em')),
                ('forma', models.CharField(max_length=30, verbose_name='Forma')),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('gateway', 'Gateway'), ('legacy', 'Legado')], max_length=16, verbose_name='Origem')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('reversed', 'Estornado')], default='confirmed', max_length=16, verbose_name='Status')),
                ('identificador_externo', models.CharField(blank=True, max_length=128, null=True, verbose_name='Identificador externo')),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_estorno', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.cobranca', verbose_name='Cobrança')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_estornados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['pago_em', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.UniqueConstraint(fields=('assinatura', 'competencia'), name='cobranca_assinatura_competencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(condition=models.Q(('valor_original__gt', 0)), name='cobranca_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(condition=models.Q(('fim_carencia__gte', models.F('vencimento'))), name='cobranca_carencia_apos_vencimento'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('dia_vencimento__gte', 1), ('dia_vencimento__lte', 28)), name='finance_config_dia_vencimento_1_28'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('dias_carencia__gte', 0)), name='finance_config_carencia_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='configuracaofinanceira',
            constraint=models.CheckConstraint(condition=models.Q(('pk', 1)), name='finance_config_singleton_pk'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='pagamento_valor_positivo'),
        ),
    ]
