# Generated by Django 5.2.11 on 2026-09-20 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provedor', models.CharField(max_length=16, verbose_name='Provedor')),
                ('id_evento_externo', models.CharField(max_length=200, verbose_name='ID do evento externo')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='Hash do payload')),
                ('payload_protegido', models.JSONField(blank=True, default=dict, help_text='Snapshot sem segredos, itens pessoais ou valores completos.')),
                ('status', models.CharField(choices=[('processado', 'Processado'), ('duplicado', 'Duplicado'), ('erro', 'Erro'), ('ignorado', 'Ignorado')], default='processado', max_length=16, verbose_name='Status')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('erro', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Evento de gateway',
                'verbose_name_plural': 'Eventos de gateway',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='provedor_gateway',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='ContaGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('provedor', models.CharField(choices=[('efi', 'Efí'), ('sicredi', 'Sicredi'), ('sicoob', 'Sicoob')], max_length=16, verbose_name='Provedor')),
                ('ambiente', models.CharField(choices=[('sandbox', 'Sandbox'), ('producao', 'Produção')], default='sandbox', max_length=16, verbose_name='Ambiente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('habilita_boleto', models.BooleanField(default=False, verbose_name='Boleto')),
                ('habilita_pix', models.BooleanField(default=False, verbose_name='PIX')),
                ('configuracao_publica', models.JSONField(blank=True, default=dict, verbose_name='Configuração pública')),
                ('configuracao_criptografada', models.TextField(blank=True, default='', verbose_name='Configuração criptografada')),
                ('ultima_conexao_status', models.CharField(blank=True, default='', max_length=64, verbose_name='Última conexão')),
                ('ultima_conexao_em', models.DateTimeField(blank=True, null=True, verbose_name='Última conexão em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_gateway_alteradas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_gateway_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta de gateway',
                'verbose_name_plural': 'Contas de gateway',
                'ordering': ['provedor', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EmissaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio', models.CharField(max_length=10, verbose_name='Meio')),
                ('chave_idempotencia', models.CharField(max_length=100, unique=True, verbose_name='Chave de idempotência')),
                ('id_externo', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID externo')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('issued', 'Emitida'), ('paid', 'Paga'), ('cancelled', 'Cancelada'), ('failed', 'Falhou'), ('pending_unknown', 'Pendente desconhecido')], default='requested', max_length=16, verbose_name='Status')),
                ('vencimento_externo', models.DateField(blank=True, null=True)),
                ('boleto_url', models.CharField(blank=True, max_length=500, null=True)),
                ('linha_digitavel', models.CharField(blank=True, max_length=100, null=True)),
                ('pix_copia_e_cola', models.TextField(blank=True, null=True)),
                ('erro_normalizado', models.CharField(blank=True, default='', max_length=255, verbose_name='Erro normalizado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissoes', to='financeiro.cobranca', verbose_name='Cobrança')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissoes', to='financeiro.contagateway', verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Emissão de cobrança',
                'verbose_name_plural': 'Emissões de cobrança',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='emissao_gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='financeiro.emissaocobranca'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('origem', 'gateway')), fields=('provedor_gateway', 'identificador_externo'), name='pagamento_gateway_provedor_externo_unico'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origem', 'gateway'), _negated=True), models.Q(('emissao_gateway__isnull', False), ('provedor_gateway__isnull', False)), _connector='OR'), name='pagamento_gateway_tem_proveniencia'),
        ),
        migrations.AddField(
            model_name='eventogateway',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='financeiro.contagateway', verbose_name='Conta'),
        ),
        migrations.AddConstraint(
            model_name='emissaocobranca',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('requested', 'issued'))), fields=('cobranca',), name='emissao_ativa_unica_por_cobranca'),
        ),
        migrations.AddConstraint(
            model_name='emissaocobranca',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('id_externo', ''), _negated=True), models.Q(('id_externo', None), _negated=True)), fields=('conta', 'id_externo'), name='emissao_id_externo_por_conta_unico'),
        ),
        migrations.AddConstraint(
            model_name='eventogateway',
            constraint=models.UniqueConstraint(fields=('provedor', 'id_evento_externo'), name='evento_gateway_provedor_evento_unico'),
        ),
    ]
