# Generated by Django 5.2.11 on 2026-09-21 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_eventogateway_pagamento_provedor_gateway_and_more'),
        ('integracoes', '0002_assinaturaorigemcobranca_assinaturareferenciaexterna_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='integracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='integracoes.integracaolegado'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.UniqueConstraint(condition=models.Q(('origem', 'legacy')), fields=('integracao', 'identificador_externo'), name='pagamento_legado_integracao_externo_unico'),
        ),
        migrations.AddConstraint(
            model_name='pagamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origem', 'legacy'), _negated=True), ('integracao__isnull', False), _connector='OR'), name='pagamento_legado_tem_integracao'),
        ),
    ]
