# Generated by Django 5.2.11 on 2026-09-20 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoLegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('escopos', models.JSONField(blank=True, default=list)),
                ('limite_requisicoes', models.PositiveIntegerField(default=60, help_text='Requisições por minuto (1 a 10000).')),
                ('redes_permitidas', models.JSONField(blank=True, default=list, help_text='Lista de CIDRs; vazio permite qualquer origem.')),
                ('credencial_expira_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integracoes_alteradas', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='integracao_legado', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integracoes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integração legada',
                'verbose_name_plural': 'Integrações legadas',
                'ordering': ['nome'],
            },
        ),
    ]
