# Generated by Django 5.2.11 on 2026-09-21 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_eventogateway_pagamento_provedor_gateway_and_more'),
        ('integracoes', '0001_initial'),
        ('licencas', '0011_alter_clientesistema_periodicidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaOrigemCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origem_cobranca', to='licencas.clientesistema')),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_sob_origem', to='integracoes.integracaolegado')),
            ],
            options={
                'verbose_name': 'Origem de cobrança da assinatura',
            },
        ),
        migrations.CreateModel(
            name='AssinaturaReferenciaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('proprietaria', models.BooleanField(default=False)),
                ('versao_externa', models.CharField(blank=True, max_length=64, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_externas', to='licencas.clientesistema')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='integracoes.integracaolegado')),
            ],
            options={
                'verbose_name': 'Referência externa de assinatura',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('integration', 'external_id'), name='integracoes_assinaturareferenciaexterna_integracao_externo_unico'), models.UniqueConstraint(condition=models.Q(('proprietaria', True)), fields=('assinatura',), name='assinatura_referencia_proprietaria_unica')],
            },
        ),
        migrations.CreateModel(
            name='ClienteReferenciaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('proprietaria', models.BooleanField(default=False)),
                ('versao_externa', models.CharField(blank=True, max_length=64, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_externas', to='licencas.cliente')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='integracoes.integracaolegado')),
            ],
            options={
                'verbose_name': 'Referência externa de cliente',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('integration', 'external_id'), name='integracoes_clientereferenciaexterna_integracao_externo_unico'), models.UniqueConstraint(condition=models.Q(('proprietaria', True)), fields=('cliente',), name='cliente_referencia_proprietaria_unica')],
            },
        ),
        migrations.CreateModel(
            name='CobrancaReferenciaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('proprietaria', models.BooleanField(default=False)),
                ('versao_externa', models.CharField(blank=True, max_length=64, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_externas', to='financeiro.cobranca')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='integracoes.integracaolegado')),
            ],
            options={
                'verbose_name': 'Referência externa de cobrança',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('integration', 'external_id'), name='integracoes_cobrancareferenciaexterna_integracao_externo_unico'), models.UniqueConstraint(condition=models.Q(('proprietaria', True)), fields=('cobranca',), name='cobranca_referencia_proprietaria_unica')],
            },
        ),
        migrations.CreateModel(
            name='PagamentoReferenciaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('proprietaria', models.BooleanField(default=False)),
                ('versao_externa', models.CharField(blank=True, max_length=64, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='integracoes.integracaolegado')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_externas', to='financeiro.pagamento')),
            ],
            options={
                'verbose_name': 'Referência externa de pagamento',
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('integration', 'external_id'), name='integracoes_pagamentoreferenciaexterna_integracao_externo_unico'), models.UniqueConstraint(condition=models.Q(('proprietaria', True)), fields=('pagamento',), name='pagamento_referencia_proprietaria_unica')],
            },
        ),
        migrations.CreateModel(
            name='PoliticaIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.CharField(choices=[('client', 'Cliente'), ('subscription', 'Assinatura'), ('charge', 'Cobrança'), ('payment', 'Pagamento')], max_length=16)),
                ('modo', models.CharField(choices=[('scl_master', 'SCL'), ('legacy_master', 'Legado'), ('shared', 'Compartilhado')], max_length=16)),
                ('readable_fields', models.JSONField(blank=True, default=list)),
                ('writable_fields', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas', to='integracoes.integracaolegado')),
            ],
            options={
                'verbose_name': 'Política de integração',
                'verbose_name_plural': 'Políticas de integração',
                'constraints': [models.UniqueConstraint(fields=('integration', 'recurso'), name='politica_integracao_recurso_unico')],
            },
        ),
        migrations.CreateModel(
            name='RequisicaoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=64)),
                ('chave_idempotencia', models.CharField(blank=True, max_length=200, null=True)),
                ('metodo', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('estado', models.CharField(choices=[('in_progress', 'Em processamento'), ('completed', 'Concluída')], default='in_progress', max_length=16)),
                ('resposta_snapshot', models.JSONField(blank=True, default=dict)),
                ('itens_recebidos', models.PositiveIntegerField(default=0)),
                ('itens_aceitos', models.PositiveIntegerField(default=0)),
                ('itens_rejeitados', models.PositiveIntegerField(default=0)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('erro', models.CharField(blank=True, default='', max_length=255)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='integracoes.integracaolegado')),
            ],
            options={
                'verbose_name': 'Requisição de integração',
                'verbose_name_plural': 'Requisições de integração',
                'ordering': ['-pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('chave_idempotencia', ''), _negated=True), models.Q(('chave_idempotencia', None), _negated=True)), fields=('integration', 'chave_idempotencia'), name='requisicao_idempotencia_por_integracao_unica')],
            },
        ),
    ]
