# Generated by Django 5.0 on 2024-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpjcpf', models.CharField(max_length=15, verbose_name='CNPJ/CPF')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('endnumero', models.CharField(max_length=10, verbose_name='Número')),
                ('endbairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('endcomplemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('endUF', models.CharField(max_length=2, verbose_name='UF')),
                ('endcidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('endcodpais', models.IntegerField(verbose_name='Código País')),
                ('endpais', models.CharField(max_length=100, verbose_name='País')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'ordering': ['nome'],
            },
        ),
    ]
