# Generated by Django 5.0 on 2024-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0002_sistema_alter_cliente_id_clientesistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoMaquina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.IntegerField(verbose_name='Cliente')),
                ('sistema', models.IntegerField(verbose_name='Sistema')),
                ('sistemaversao', models.CharField(max_length=20, verbose_name='Versão')),
                ('usuario', models.CharField(max_length=200, verbose_name='Usuário')),
                ('estacaonome', models.CharField(max_length=200, verbose_name='Estação')),
                ('estacaomemoria', models.CharField(max_length=50, verbose_name='Memória')),
                ('estacaoprocessador', models.CharField(max_length=200, verbose_name='Processador')),
                ('estacaosistemaoperacional', models.CharField(max_length=200, verbose_name='Sistema Operacional')),
                ('estacaomac', models.CharField(max_length=100, verbose_name='MAC')),
                ('acessoip', models.CharField(max_length=20, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
            ],
            options={
                'verbose_name': 'Acessos',
                'ordering': ['cliente', 'sistema'],
            },
        ),
    ]
