# Generated by Django 5.2.11 on 2026-09-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0003_acessomaquina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessomaquina',
            options={'ordering': ['cliente', 'sistema'], 'verbose_name': 'Acesso'},
        ),
    ]
