# Generated by Django 5.2.11 on 2026-09-20 16:49

import licencas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0004_alter_acessomaquina_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bloqueado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado em'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_bloqueio',
            field=models.TextField(blank=True, default='', verbose_name='Motivo do bloqueio'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='codigo',
            field=models.SlugField(blank=True, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='sistema',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpjcpf',
            field=models.CharField(max_length=15, validators=[licencas.validators.validate_document], verbose_name='CNPJ/CPF'),
        ),
    ]
