# Generated by Django 5.2.11 on 2026-09-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencas', '0010_subscription_final_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesistema',
            name='periodicidade',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], max_length=10, verbose_name='Periodicidade'),
        ),
    ]
